### ISSUE TITLE
Support for 'clear'?

### ISSUE THREAD

**Issue by lensco** [ded/R2#1]
Very interesting initiative. As far as I can see, nothing is done to values of the 'clear' property, right?

**Comment by ded** [comment]
this is an easy fix. the initiative is to help applications support alternate languages not in their current direction.

**Comment by lensco** [comment]
Yep, I have a bit of experience in the matter (see http://lensco.be/2010/11/05/web-design-for-right-to-left-languages/), but little experience in the GitHub thing. I have some ideas for improvements, I'll probably submit some pull requests later.

**Comment by ded** [comment]
there was a [Ruby port](https://github.com/mzsanford/R2rb) to this, and so far it's working quite well for us in the early stages here at Twitter
