### ISSUE TITLE
!important declaration not handled

### ISSUE THREAD

**Issue by ghost** [ded/R2#11]
For at least three properties that I've tried (padding, margin, float), the presence of the !important declaration results in the property not being converted.

Example:

```
padding: 0 25px 0 0 !important;
```

**Comment by mhemesath** [comment]
I think this could be easily fixed by updated the quad method to handle !important. Right now it only evaluates if there are 4 matches on the values.

**Comment by ded** [comment]
ah right. this can easily be patched. if I get some time I'll have a look

**Comment by mhemesath** [comment]
@wyatt378 you shouldn't be using !important anyway :p
