### ISSUE TITLE
background-position property not handled

### ISSUE THREAD

**Issue by ghost** [ded/R2#12]
The horizontal value of the background-position property is not handled. The following two examples demonstrate this issue:

```
background: url('../img/image.png') no-repeat left center;    

background-position: left center;
```

What I would expect:

```
background: url('../img/image.png') no-repeat right center;    

background-position: right center;
```

Instead, the 'left' horizontal value is not converted.

The following types of horizontal values need to be supported:

**Percentage**
    30% ---> 70% (100 - x)

**Pixel**
A pixel value without a side is assumed to be anchored on the left, so:
    20px ---> right 20px

Pixel and side:
    right 20px --> left 20px

The ability to specify a side and offset is only supported in newer browsers (see "Four values syntax" under https://developer.mozilla.org/en/CSS/background-position#Browser_compatibility), so it may be desirable to simply not convert pixel values if a side is not specified.

**Side**
    left ---> right (and vice  versa)

**Comment by idosius** [comment]
Plus one.

**Comment by idosius** [comment]
Any plans to add support for this?

**Comment by ded** [comment]
this is a tricky one, but definitely needs to get in.

**Comment by ded** [comment]
fixed — will push soon.

**Comment by ded** [comment]
got this working working on `background-position` — however there has yet to be support working with the `background` shorthand property

**Comment by jasonmobley** [comment]
The background-position property can have multiple values separated by commas to support positioning multiple background images/gradients.

For example,

``` css
background-image: url(image1.png), url(image2.png);
background-position: left 20px center, left 40px center;
```

The changes in f690519bd15c138b0031bae961c85c8ebc3e9d83 only change the first "left" to "right" in the above code. Ideally it would change both.
