### ISSUE TITLE
how can I make the output not be minified ? 

### ISSUE THREAD

**Issue by dorongutman** [ded/R2#18]

**Comment by fitzchak** [comment]
I'm also interested in knowing that.
In addition, does this project is maintained?

**Comment by ded** [comment]
i could probably add in some work to have it not minified... which is probably the way it should have been from the start. and yes, it does get maintained :)

**Comment by fitzchak** [comment]
Great!

**Comment by fitzchak** [comment]
This is really needed in order to be able to use diff tools.
