### ISSUE TITLE
How can I make R2 to skip a section in the css file? 

### ISSUE THREAD

**Issue by fitzchak** [ded/R2#19]
Some context in the CSS file should be the same across all languages, is there a way to tell R2 to not convert this section from LTR to RTL?

**Comment by alimd** [comment]
I have same problem !
Request future: use some comment for some properties or css section to prevent converted to rtl
thank you

**Comment by n0nick** [comment]
:+1:

**Comment by monshi** [comment]
Is there any plan to support opt outs? for example similar to CSSJanus that you can add this comment /\* @noflip */ before a selector to skip it.

**Comment by ded** [comment]
yeah. we should prioritize this since quite a few folks need this, hence the existence in CSSJanus

**Comment by BYK** [comment]
We can even introduce declaration-level "noflip` if there's demand for it now.
