### ISSUE TITLE
please help me to run r2

### ISSUE THREAD

**Issue by KiarashS** [ded/R2#2]
hi;
this error:

> var output=require('r2').swap('node_modules/r2/bootstrap.css');
> TypeError: Cannot call method 'map' of null
>     at r2 (C:\Program Files (x86)\nodejs\node_modules\r2\r2.js:75:49)
>     at Object.swap (C:\Program Files (x86)\nodejs\node_modules\r2\r2.js:111:10)
>     at repl: 1:26
>     at REPLServer.eval (repl.js:80:21)
>     at repl.js:190:20
>     at REPLServer.eval (repl.js:87:5)
>     at Interface.<anonymous> (repl.js:182:12)
>     at Interface.emit (events.js:67:17)
>     at Interface._onLine (readline.js:162:10)
>     at Interface._line (readline.js:426:8)

please describe install r2 in nodejs from first step by step.
very thanx.

**Comment by dustinsmith1024** [comment]
Did you trying running in from the command line?  Something like: r2 bootstrap.css new_file.css

Looks like your trying to run it from another node app above.  In which case you need to read in the file and pass the contents of the file to .swap() not a file name.
