### ISSUE TITLE
r2 command not working in ubuntu 13.04 

### ISSUE THREAD

**Issue by rchod** [ded/R2#25]
i tried excuting the r2 command on ubuntu 13.04, but it did not work, but when i cheked on windows it works just fine.

```
$ ls -l /usr/local/bin/r2
lrwxrwxrwx 1 root root 29 Sep 19 18:54 /usr/local/bin/r2 -> ../lib/node_modules/R2/bin/r2
```

**Comment by BYK** [comment]
Can you be more specific? What is the error you get?

**Comment by rchod** [comment]
i fixed the problem it was a conflict between node and nodejs as mentionned here http://askubuntu.com/questions/235655/node-js-conflicts-sbin-node-vs-usr-bin-node
because i installed node with apt-get and then installed another node mannually. now r2 works fine !

**Comment by BYK** [comment]
Awesome!
