### ISSUE TITLE
Enable TravisCI for the repo

### ISSUE THREAD

**Issue by BYK** [ded/R2#28]
TravisCI for the repo is still not enable. Either the hook is missing or it's not enabled in https://travis-ci.org/profile

**Comment by ded** [comment]
here's what it is showing http://cl.ly/image/0X302R312A1O

**Comment by ded** [comment]
the service hook is also enabled

**Comment by BYK** [comment]
Then may be the token is old/invalid since when I forked the project, it worked for me: https://travis-ci.org/BYK/R2/builds/16307241

**Comment by BYK** [comment]
Alright, it looks like fixed! I guess it was waiting for a payload which was triggered with my latest commit.

:beers:

**Comment by ded** [comment]
cool. this has been working out great. thanks for getting this up and working!
