### ISSUE TITLE
problem with CSS3 Property?

### ISSUE THREAD

**Issue by assaqqaf** [ded/R2#3]
I thing it doesn't support CSS3 Property, like: border-radius,...

I try with twitter bootstrap, I found it not completely converted I think for above reason.
 thank you

**Comment by mhemesath** [comment]
+1 I'm encountering this issue as well.  The following block doesn't convert:

```
.btn-group > .btn:last-child,
.btn-group > .dropdown-toggle {
  -webkit-border-top-right-radius: 4px;
          border-top-right-radius: 4px;
  -webkit-border-bottom-right-radius: 4px;
          border-bottom-right-radius: 4px;
  -moz-border-radius-topright: 4px;
  -moz-border-radius-bottomright: 4px;
}
```

**Comment by mhemesath** [comment]
I think this is resolved. The problem was the latest code wasn't deployed to NPM when I encountered this issue. @assaqqaf can you verify if this is still an issue?

**Comment by assaqqaf** [comment]
sorry i forgot to close this request. I solve this problem. now its work
